[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[healthcheck]]
path = "/health"
port = 3000

